/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as TravauxProjectIdRouteImport } from './routes/travaux.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TravauxProjectIdRoute = TravauxProjectIdRouteImport.update({
  id: '/travaux/$projectId',
  path: '/travaux/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/travaux/$projectId': typeof TravauxProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/travaux/$projectId': typeof TravauxProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/travaux/$projectId': typeof TravauxProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/services/$serviceId' | '/travaux/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/services/$serviceId' | '/travaux/$projectId'
  id: '__root__' | '/' | '/services/$serviceId' | '/travaux/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  TravauxProjectIdRoute: typeof TravauxProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travaux/$projectId': {
      id: '/travaux/$projectId'
      path: '/travaux/$projectId'
      fullPath: '/travaux/$projectId'
      preLoaderRoute: typeof TravauxProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  TravauxProjectIdRoute: TravauxProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
